#include "src/algorithm/size.cpp"
#include "src/functional/is_invocable.cpp"
#include "src/functional/bind.cpp"
#include "src/functional/invoke.cpp"
#include "src/number/is_number.cpp"
#include "src/list/join.cpp"
#include "src/list/enumerate.cpp"
