#pragma once

#include <jln/mp/smp/functional/bind.hpp>
#include <jln/mp/smp/functional/capture.hpp>
#include <jln/mp/smp/functional/cascade.hpp>
#include <jln/mp/smp/functional/compose.hpp>
#include <jln/mp/smp/functional/each.hpp>
#include <jln/mp/smp/functional/eval.hpp>
#include <jln/mp/smp/functional/fix.hpp>
#include <jln/mp/smp/functional/flip.hpp>
#include <jln/mp/smp/functional/identity.hpp>
#include <jln/mp/smp/functional/if.hpp>
#include <jln/mp/smp/functional/invoke_twice.hpp>
#include <jln/mp/smp/functional/is_invocable.hpp>
#include <jln/mp/smp/functional/lift.hpp>
#include <jln/mp/smp/functional/on.hpp>
#include <jln/mp/smp/functional/partial.hpp>
#include <jln/mp/smp/functional/recurse.hpp>
#include <jln/mp/smp/functional/sfinaefwd.hpp>
#include <jln/mp/smp/functional/tee.hpp>
