#pragma once

#include <jln/mp/algorithm/accumulate.hpp>
#include <jln/mp/algorithm/after.hpp>
#include <jln/mp/algorithm/all_of.hpp>
#include <jln/mp/algorithm/anticirculant_matrix.hpp>
#include <jln/mp/algorithm/any_of.hpp>
#include <jln/mp/algorithm/arrange.hpp>
#include <jln/mp/algorithm/before.hpp>
#include <jln/mp/algorithm/before_after.hpp>
#include <jln/mp/algorithm/circulant_matrix.hpp>
#include <jln/mp/algorithm/collapse.hpp>
#include <jln/mp/algorithm/combine.hpp>
#include <jln/mp/algorithm/compare_with.hpp>
#include <jln/mp/algorithm/compress.hpp>
#include <jln/mp/algorithm/conjunction.hpp>
#include <jln/mp/algorithm/contains.hpp>
#include <jln/mp/algorithm/copy.hpp>
#include <jln/mp/algorithm/copy_unique.hpp>
#include <jln/mp/algorithm/count.hpp>
#include <jln/mp/algorithm/counter.hpp>
#include <jln/mp/algorithm/disjunction.hpp>
#include <jln/mp/algorithm/drop_until.hpp>
#include <jln/mp/algorithm/drop_until_xs.hpp>
#include <jln/mp/algorithm/drop_while.hpp>
#include <jln/mp/algorithm/drop_while_xs.hpp>
#include <jln/mp/algorithm/ends_with.hpp>
#include <jln/mp/algorithm/find.hpp>
#include <jln/mp/algorithm/find_last.hpp>
#include <jln/mp/algorithm/flatten.hpp>
#include <jln/mp/algorithm/fold.hpp>
#include <jln/mp/algorithm/fold_right.hpp>
#include <jln/mp/algorithm/fold_tree.hpp>
#include <jln/mp/algorithm/fold_xs.hpp>
#include <jln/mp/algorithm/group.hpp>
#include <jln/mp/algorithm/group_n.hpp>
#include <jln/mp/algorithm/index.hpp>
#include <jln/mp/algorithm/indices.hpp>
#include <jln/mp/algorithm/intersperse.hpp>
#include <jln/mp/algorithm/iota.hpp>
#include <jln/mp/algorithm/is_disjoint.hpp>
#include <jln/mp/algorithm/is_sorted.hpp>
#include <jln/mp/algorithm/is_subset.hpp>
#include <jln/mp/algorithm/is_unique.hpp>
#include <jln/mp/algorithm/lexicographical_compare.hpp>
#include <jln/mp/algorithm/lower_bound.hpp>
#include <jln/mp/algorithm/make_int_sequence.hpp>
#include <jln/mp/algorithm/matrix_longest.hpp>
#include <jln/mp/algorithm/matrix_shortest.hpp>
#include <jln/mp/algorithm/merge.hpp>
#include <jln/mp/algorithm/mismatch.hpp>
#include <jln/mp/algorithm/mismatch_index.hpp>
#include <jln/mp/algorithm/none_of.hpp>
#include <jln/mp/algorithm/pairwise.hpp>
#include <jln/mp/algorithm/pairwise_fold.hpp>
#include <jln/mp/algorithm/partition.hpp>
#include <jln/mp/algorithm/permutations.hpp>
#include <jln/mp/algorithm/powerset.hpp>
#include <jln/mp/algorithm/prefix.hpp>
#include <jln/mp/algorithm/product.hpp>
#include <jln/mp/algorithm/regroup.hpp>
#include <jln/mp/algorithm/remove.hpp>
#include <jln/mp/algorithm/remove_adjacent.hpp>
#include <jln/mp/algorithm/remove_unique.hpp>
#include <jln/mp/algorithm/repeat.hpp>
#include <jln/mp/algorithm/replace.hpp>
#include <jln/mp/algorithm/reverse.hpp>
#include <jln/mp/algorithm/reverse_fold.hpp>
#include <jln/mp/algorithm/reverse_fold_right.hpp>
#include <jln/mp/algorithm/rotate.hpp>
#include <jln/mp/algorithm/same.hpp>
#include <jln/mp/algorithm/scan.hpp>
#include <jln/mp/algorithm/scan_right.hpp>
#include <jln/mp/algorithm/search.hpp>
#include <jln/mp/algorithm/similar.hpp>
#include <jln/mp/algorithm/skip_until.hpp>
#include <jln/mp/algorithm/skip_until_xs.hpp>
#include <jln/mp/algorithm/skip_while.hpp>
#include <jln/mp/algorithm/skip_while_xs.hpp>
#include <jln/mp/algorithm/sort.hpp>
#include <jln/mp/algorithm/split.hpp>
#include <jln/mp/algorithm/split_after.hpp>
#include <jln/mp/algorithm/split_at.hpp>
#include <jln/mp/algorithm/split_before.hpp>
#include <jln/mp/algorithm/split_from.hpp>
#include <jln/mp/algorithm/starts_with.hpp>
#include <jln/mp/algorithm/suffix.hpp>
#include <jln/mp/algorithm/take_until.hpp>
#include <jln/mp/algorithm/take_until_xs.hpp>
#include <jln/mp/algorithm/take_while.hpp>
#include <jln/mp/algorithm/take_while_xs.hpp>
#include <jln/mp/algorithm/transform.hpp>
#include <jln/mp/algorithm/transform_first.hpp>
#include <jln/mp/algorithm/transform_second.hpp>
#include <jln/mp/algorithm/transform_third.hpp>
#include <jln/mp/algorithm/unfold.hpp>
#include <jln/mp/algorithm/unique.hpp>
#include <jln/mp/algorithm/upper_bound.hpp>
#include <jln/mp/algorithm/zip.hpp>
#include <jln/mp/algorithm/zip_longest.hpp>
