#pragma once

#include <jln/mp/functional/bind.hpp>
#include <jln/mp/functional/call.hpp>
#include <jln/mp/functional/capture.hpp>
#include <jln/mp/functional/cascade.hpp>
#include <jln/mp/functional/compose.hpp>
#include <jln/mp/functional/each.hpp>
#include <jln/mp/functional/eval.hpp>
#include <jln/mp/functional/fix.hpp>
#include <jln/mp/functional/flip.hpp>
#include <jln/mp/functional/identity.hpp>
#include <jln/mp/functional/if.hpp>
#include <jln/mp/functional/invoke_twice.hpp>
#include <jln/mp/functional/is_invocable.hpp>
#include <jln/mp/functional/lift.hpp>
#include <jln/mp/functional/memoize.hpp>
#include <jln/mp/functional/monadic.hpp>
#include <jln/mp/functional/not_fn.hpp>
#include <jln/mp/functional/on.hpp>
#include <jln/mp/functional/partial.hpp>
#include <jln/mp/functional/recursively.hpp>
#include <jln/mp/functional/tee.hpp>
#include <jln/mp/functional/try.hpp>
#include <jln/mp/functional/while.hpp>
